### PR TITLE
Updating and removing code from editor.html + css

### PR DESCRIPTION
**Pull request by Starbors**
Fixed some bugs with this code :)

### CODE REVIEW

**Comment by Starbors** [comment]
l hope this code can help!

**Comment by Starbors** [comment]
+ fixed some css

**Comment by givanz** [comment]
Found this in the pull request
```
<p>Playing with <a href="https://ruwix.com/" rel="nofollow noopener">twisty puzzles</a> is the best way of improving your dexterity and problem solving skills.</p>
```
Please don't spam.

**Comment by Ryan-da-ghost** [comment]
@givanz The pull Request Code was Made by a HTML/CSS validator. The Ad Was from the validator. honestly It's a VERY Smart way to advertise and Get money like this

**Pull request closed without merging**
